config/routes.rb
OilChange::Application.routes.draw do

  resources :cars

  root :to => ':cars#index'

  scope :module => "car" do
    resources :makes, :models, :mileage, :year
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
    has_many :makes

	#def year
#
	#	"#{self[:year].uniq}"
	#end 



end

app/models/make.rb
class Make < ActiveRecord::Base
   	belongs_to :car

	#def year
#
	#	"#{self[:year].uniq}"
	#end 



end

app/models/mileage.rb
class Mileage < ActiveRecord::Base
    belongs_to :model

	#def year
#
	#	"#{self[:year].uniq}"
	#end 



end

app/models/model.rb
class Model < ActiveRecord::Base
   	belongs_to :makes

	#def year
#
	#	"#{self[:year].uniq}"
	#end 



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :make, :mileage, :model, :year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    #@cars = Car.all
  #@cars = Car.all.uniq
  @years = Car.select(:Year).uniq
  @makes = Car.select(:Make).uniq
  @models = Car.select(:Model).uniq
  #@cars = Car.where("Year = ?", params[:year])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end


#GET cars
#
def loadData

  if !params[:year]

      params[:year]= 2013

  end
  @car = Car.where("year = ?", params[:year]).uniq

  respond_to do |format|
    format.html
    format.json{ render json:car}
  end

end


end

app/controllers/makes_controller.rb
class MakesController < ApplicationController

	respond_to :html, :json

	def index

    if !params[:Year].empty?

      @carMakes = Car.select(:Make).where("Year=?", params[:Year]).uniq

 		respond_with(@carMakes)



    end

	end

end

app/controllers/mileage_controller.rb
class MileageController < ApplicationController

	respond_to :html, :json

	def index
    if !params[:Year].empty? && !params[:Models].empty?

      @carMileage = Car.select(:Mileage).where("Model=? AND Year=?", params[:Models], params[:Year])

      respond_with(@carMileage)
#
    end
	end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController

	respond_to :html, :json

	def index

		if !params[:Year].empty? || !params[:Makes].empty?

	      @carModels = Car.select(:Model).where("Make=? AND Year=?", params[:Makes], params[:Year])

	      respond_with(@carModels)
	

		end

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/make_helper.rb
module MakeHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/mileage_helper.rb
module MileageHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<%content_for :head do %>

<script type="text/javascript">


  function capitalizeFirstLetter(string){
    return string.charAt(0).toUpperCase() + string.slice(1);
  }

  $(document).ready(function(){

    if($("#year option:selected").text() == "")
    {
      $("#makes").prop('disabled', 'disabled');
      $("#models").prop('disabled', 'disabled');
    }


    $("select").on('change', function(e){

    var valuesToSubmit = e.currentTarget.selectedOptions[0].innerText;

    var form = document.getElementsByTagName('form');

    var target = capitalizeFirstLetter(e.target.name);

    var controller;

    switch(target){

      case 'Year':
        controller = "makes"
        break;

      case 'Makes':
        controller = "models"
        valuesToSubmit += '&Year=' + $("#year option:selected").text();
        break;

      case 'Models':
        controller = "mileage"
        valuesToSubmit += '&Year=' + $("#year option:selected").text();
        break;
    };


    $.ajax({
        url: controller + ".json", //sumbits it to the given url of the form
        data: target +'=' + valuesToSubmit,
        dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
    }).success(function(json){
        //act on result.

        var length = json.length;

        if(length > 1){

        option = capitalizeFirstLetter(controller);

        option = option.indexOf('s') > 0 ? option.substr(0, option.indexOf('s')) : option;


        var arrOptions = [$('<option/>')];

        for(var i=0; i < length; i++){
          var newOption = $('<option/>');
          newOption.text(json[i]["" + option + ""]);
          newOption.attr('value', json[i]["" + option + ""]);
          arrOptions.push(newOption);
        }

        $("#" + controller + "").html(arrOptions);
        $("#" + controller + "").prop('disabled', false);
      }
      else
      {
        //Display mileage for vehicle.
        $("#mileage").text(json[0].Mileage);
      }
    });
    return false; // prevents normal behaviour


    });


  });

</script>

<% end %>


<div id="oilChangeApp">


<%= form_tag("car/makes", :method => "get", :remote => true) do %>

<%= select_tag 'year', options_from_collection_for_select(@years, 'ID', 'Year'), { :include_blank => true} %>

<%= select_tag 'makes', options_from_collection_for_select(@makes, 'ID', 'Make'), { :include_blank => true} %>

<%= select_tag 'models', options_from_collection_for_select(@models, 'ID', 'Model'), { :include_blank => true} %>

<% end %>

<div id="mileage"></div>

</div>

app/views/cars/list.html.erb
<%content_for :head do %>

<script type="text/javascript">
  
  $(document).ready(function(){


    $("#car").on('change', function(e){

    var valuesToSubmit = e.currentTarget.selectedOptions[0].innerText;

    var form = document.getElementsByTagName('form');

    $.ajax({
        url: form[0].action + ".json", //sumbits it to the given url of the form
        data: 'Year=' + valuesToSubmit,
        dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
    }).success(function(json){
        //act on result.
        console.log(json);
    });
    return false; // prevents normal behaviour


    })


  })

</script>

<% end %>


<div id="oilChangeApp">


<%= form_tag("/cars", :method => "get", :remote => true) do %>

<%= select_tag 'year', options_from_collection_for_select(@years, 'ID', 'Year') %>

<%= select_tag 'make', options_from_collection_for_select(@makes, 'ID', 'Make') %>

<%= select_tag 'model', options_from_collection_for_select(@models, 'ID', 'Model') %>

<% end %>
</div>

app/views/cars/loadData.html.erb
<div id="oilChangeApp">

<% if false %>
<% @cars.each do |car| %>

  <select id="dd_year">
    <option>
      
    </option>
  </select>

<% end %>
<% end %>

<%= form_tag @car, :url => { :action => "index" }, :html => {:class => 'oil_change_form'} do |f| %>
  
<%= collection_select(:car, :year, Car.all, :id, :year)

<% end %>
</div>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OilChange</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :mileage %><br />
    <%= f.number_field :mileage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Mileage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.year %></td>
    <td><%= user.make %></td>
    <td><%= user.model %></td>
    <td><%= user.mileage %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @user.year %>
</p>

<p>
  <b>Make:</b>
  <%= @user.make %>
</p>

<p>
  <b>Model:</b>
  <%= @user.model %>
</p>

<p>
  <b>Mileage:</b>
  <%= @user.mileage %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>